### PR TITLE
handel continuous multiperiod mpds

### PR DESCRIPTION
**Pull request by joywelt**
config: add cperiods_xx in the URL

### CODE REVIEW

**Comment by TobbeMobiTV** [comment]
@joywelt. Thanks for your PR. I haven't looked at the details yet, but in general it looks fine. Before accepting any code, I'd like to know if your company is a member of DASH-IF? In case not, you'll need to fill in a copyright form (similar to what is used for dash.js).

**Comment by waqarz** [comment]
@TobbeMobiTV yes, we're DASH-IF member,

**Comment by joywelt** [comment]
@TobbeMobiTV yes, I work with @waqarz

**Comment by TobbeMobiTV** [comment]
Sorry for the delay. Here is my response:

I've looked at the code, and the commits, and would like to see the following changes.
1) Regarding the implementation, it is a lot of repetition between cperiods and periods. I think it would be cleaner to add a new parameter /continuous_1/ which is just an extra flag together with /periods_X/
In that case, there is much less code repetition needed, and there is essentially only new value to pass around.
2) The tests should pass, which they don't
     Go to top directory and run ./run_tests.sh
3) For a new feature like this, I'd like to see a test in dashlivesim/tests that checks that it is working. For example, a variant of test_dash_proxy.TestMediaSegments.testMultiPeriod that checks that the output has the continous data.
4) pylint should be run to and the score 10.0 should still be valid for the source files (not the tests)
5) I'd like the commit history of the PR to be nicer. The process for a PR should be that you make a new branch: `feature_continuous_periods`or something similar and **rebase** that branch on the latest upstream development commit (don't use git merge).
6). Don't check in the updated .gitignore file

Does this sound OK to you? I look forward to an updated or new PR.

**Comment by joywelt** [comment]
@TobbeMobiTV 
Sorry I was on vacation and just came back today. Here are some comments to your response:
1) the code I wrote added a new parameter /cperiod_Y/. Although it seems to share a lot with period_X, they are actually almost independent. Only when they are both present, cperiod_Y would overwrite period_X, as it's only possible to have one period setting. To avoid misunderstanding or confusion, I'll change cperiod to continuous. 
2) I'll check the reason and make necessary changes.
3-6) Ok, I'll write a test script, check with pylint and make the new PR nicer.

**Pull request closed without merging**
