### PR TITLE
Early-terminated-periods feature implemented.

### PR DESCRIPTION
**Pull request by AdithyanIlangovan**
For details about this PR, please refer to the following document : 
>[earlyTerminatedPeriod.pdf](https://github.com/Dash-Industry-Forum/dash-live-source-simulator/files/103048/earlyTerminatedPeriod.pdf)

What follows is a summary of the details present in the document.

* We are creating early terminated periods in the dash-live-simulator.
* We achieve this by passing two argument to the url like so :
 * http://server/livesim/periods_60/etp_10/etpDuration_10/Manifest.mpd
* The above url implies two things:
 *  How often the early terminated periods are created ?  For example, etp_10 implies 10 early terminated periods (ETPs) are created in one hour.
 * When is this period terminated ? For example, etpDuration_10 implies each ETP is terminated at 10 seconds.
* A robust unit test (we extract the .xml parameters) is also written with this commit.
* All possible combination of values for etp and etpDuration are not possible, invalid combinations raise an exception.

### CODE REVIEW

**Comment by AdithyanIlangovan** [comment]
@TobbeMobiTV  I had started developing the early-terminated-period-feature immediately after the xlink-feature. When I was working on early-terminated-feature, the xlink feature was not yet merged.
So, I believe for this reason, the branches have conflicts.
* To avoid this conflicts in future, what do you recommend me to do?

Whenever I start working on a feature, should I always start from the latest develop branch.
I am new to git, so I am sorry if the answer to the question is a bit obvious.

**Comment by waqarz** [comment]
@AdithyanIlangovan The solution here seems to be a good option: http://stackoverflow.com/questions/12770550/my-pull-request-has-been-merged-what-to-do-next

**Comment by TobbeMobiTV** [comment]
@AdithyanIlangovan 
Yes, something like that.

Pull develop from the Dash-Industry-Forum remote and push it to your fork.
Make a new branch in your fork for each thing you work on. If it is a new feature, please call it feature-...., while fix-... is a good name for a bug fix.

As the central develop branch evolves, rebase your branch on the latest develop commit. That is a local process. Then you should push your rebase to your fork repo. You need to use --force flag for that.

**Comment by waqarz** [comment]
@TobbeEdgeware , @AdithyanIlangovan is a new PR required for it after updated to resolve conflicts?

**Comment by TobbeEdgeware** [comment]
@waqarz @AdithyanIlangovan A new PR is not needed. Github tracks the PR branch and automatically checks if the conflicts have been resolved.

**Comment by AdithyanIlangovan** [comment]
@TobbeEdgeware  Should I resolve the conflicts for this PR branch? Or would you be merging them manually. Please let me know.

**Comment by TobbeEdgeware** [comment]
@AdithyanIlangovan I'd prefer that you rebase your changes on the latest central development commit and fix all conflicts and then push your changes so that github will tell that your branch has no conflicts.

**Pull request closed without merging**
