### PR TITLE
Support for insertion of different type of AD's (new)

### PR DESCRIPTION
**Pull request by AdithyanIlangovan**
For detailed description about this PR, refer the following document.
>[adinsertion.pdf](https://github.com/Dash-Industry-Forum/dash-live-source-simulator/files/115652/adinsertion.pdf)

What follows is a summary of the above document.

* The current version of the live-source-simulator supports xlink remote periods.
But the periods that xlink refer to are part of the live content itself. Instead of
xlinks referring to the its own content, we want the xlinks to refer to on-demand
ads now.

* In this PR, we extend the functionality to insert on-demand ADs.

* In this PR, I have also implemented features that will help to insert on demand ADs.

   -  Duration attribute before AD's

   -  Asset identifier for continuous periods

### CODE REVIEW

**Comment by TobbeEdgeware** [comment]
@AdithyanIlangovan I'd like to have this PR rebased on the latest development commit and one or more tests added to make sure that this feature is working and that is not getting broken later on by other modifications. You can use a git push --force to update the branch on your fork after you have rebased, so that you can avoid making a new PR.

**Comment by AdithyanIlangovan** [comment]
@TobbeEdgeware I have rebased and also added a test. The test run successfully from my side. 
In the **Files Changed** window, it shows 75 files changed, although I changed only four files. I guess this is because of rebasing (it shows file mode changed). And I hope this is not a problem.

**Comment by TobbeEdgeware** [comment]
No, its not acceptable that 75 files have changed. For some reason all the files have gotten the executable bit set, and there is no reason to have that bit set for all the text files.. Rebase does not do this, so it must have been some other process. There is also a lot of new content in the file cc_inserter/__init__.py file. A whole HTML page has been included there. This also should not be in the commit.

A clean 'git rebase' command line call should not cause any issues beyond that your history in that branch is rewritten and there may be some merging problems that you need to handle. If you want to keep track of what you did before the rebase, you can make an extra branch that keeps track of the state. You can also go back to that state if you remember the commit ID since nothing is thrown away by git (unless garbage-collected at some stage).

So, please try to clean this so that you only get the files changed which should be changed. If you don't manage, I may try to cherry-pick just the essential changes and skip the rest of the Pull Request.

**Comment by AdithyanIlangovan** [comment]
@TobbeEdgeware  I cleaned up according to your suggestions and created a new PR. It was easier for me to create a new pull request. I hope it is okay.

**Pull request closed without merging**
