### PR TITLE
Feature mpd callback event

### PR DESCRIPTION
**Pull request by AdithyanIlangovan**
For details of this PR, please refer to the following document : [mpdcallback.pdf](https://github.com/Dash-Industry-Forum/dash-live-source-simulator/files/457092/mpdcallback.pdf).

A summary of the above document:

- Callback event is signalled in the MPD by adding a EventStream element at the period level.
- Example usage : **http://........./periods_60/mpdcallback_30/.......Manifest.mpd**, this creates 60 periods per hour, out of which 30 periods per hour have mpdcallback eventstreams at the period level.

Code has been implemented along with pylint checks and a testmodule is also written.

### CODE REVIEW

**Comment by AdithyanIlangovan** [comment]
Hi @TobbeEdgeware @TobbeMobiTV ,
Any update on this PR? 
If it is OK and if it is merged, I would like to add this to the http://testassets.dashif.org:8080/ website.

**Comment by TobbeEdgeware** [comment]
HI @AdithyanIlangovan Sorry for the delay. Will try to fix it during the weekend.

**Comment by TobbeEdgeware** [comment]
@AdithyanIlangovan I was a bit too quick in merging, since there were 3 errors in the tests introduced in commit aa1cfd2.
I've fixed this in commit 97f5bd2. Please have a look if the fix looks OK.

**Comment by AdithyanIlangovan** [comment]
@TobbeEdgeware  
Sorry, I don't remember how I missed catching that error, I thought it passed all the tests. 
The fix looks okay, thank you for the fix :) !

**Pull request merged**
