### PR TITLE
Add a new function to compress the "S" elements in SegmentTimeline

### PR DESCRIPTION
**Pull request by joywelt**
If the durations of continuous "S" elements are the same, only the first "S" element will be present with r="-1" in the mpd file. Currently this compression is done only once from the down to top, which means that if there're more than one place needed for compression in a SegmentTemplate, only the last one will be handled. This function is available when /segtimeline_1/ and /r_1/ are both present in the request URL.

### CODE REVIEW

**Comment by waqarz** [comment]
Since segment timeline is being implemented, we should review this once the implementation is done.

**Comment by TobbeEdgeware** [comment]
There is now an implementation of SegmentTimeline, and I've just put the latest commit e96c7b6 on livesim-dev. I don't see that anything needs to be added, except that publishTime should be handled better. @waqarz  What is your and your team's opinon?

**Comment by waqarz** [comment]
Great, Can we have test URL(s) where r=-1?

**Comment by TobbeEdgeware** [comment]
Where do you want the r=-1? At the last segment, or at a middle segment? If it is at the last segment, we don't even need to update the MPD.

**Comment by waqarz** [comment]
r = -1 would mean that the same element is repeated till the end of the current period. So for multi-period content, if the duration of video segments is identical for example, we could signal r = -1. This would normally only be -1 for the last S element in a period.

**Comment by TobbeEdgeware** [comment]
Sure, but I don't see that r=-1 at the end of a period gives any more run-length compression than putting an actual value of the number of repeats.

Anyway, multi-period does not seem to work well (at least not for live), since I cannot play
http://vm2.dashif.org/livesim-dev/periods_60/testpic_2s/Manifest.mpd in the latest development version of dash.js. Until $Number$-template work, there is not much use to try to test SegmentTimeline with multiple periods.

**Comment by waqarz** [comment]
yes, I mean the purpose of having this test feature is not compression but to see if a client developer has handled this option in his code

**Comment by AkamaiDASH** [comment]
Let me know when it is ready and I’ll test Dash.js.

From: waqarz
Reply-To: Dash-Industry-Forum/dash-live-source-simulator
Date: Tuesday, March 15, 2016 at 8:29 AM
To: Dash-Industry-Forum/dash-live-source-simulator
Subject: Re: [dash-live-source-simulator] Add a new function to compress the "S" elements in SegmentTimeline (#19)


yes, I mean the purpose of having this test feature is not compression but to see if a client developer has handled this option in his code

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Dash-Industry-Forum/dash-live-source-simulator/pull/19#issuecomment-196878536<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Dash-2DIndustry-2DForum_dash-2Dlive-2Dsource-2Dsimulator_pull_19-23issuecomment-2D196878536&d=CwMCaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=HMIPFyLErj4M8VUwg3x36W02236DJoh_A_hxovpfrCc&m=HmcSB4VyrbWFBPdF3Zo77Sl1zlf1Kyj7VOO6OnOJtxs&s=j27QrLlvpi37ZFSr4ddQ7odnEzozyFhEDBl_FllNXUg&e=>

**Pull request closed without merging**
